# Generated by Django 5.0.3 on 2024-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.CharField(max_length=40, verbose_name="Event Group"),
        ),
        migrations.AlterField(
            model_name="event",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["group", "timestamp"], name="eventlog_ev_group_88fa5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["timestamp"], name="eventlog_ev_timesta_2f8587_idx"
            ),
        ),
    ]
