# Generated by Django 5.0.3 on 2024-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventlog", "0002_alter_event_group_alter_event_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="Data"),
        ),
    ]
