# Generated by Django 4.2.13 on 2024-06-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0003_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Event Group'),
        ),
    ]
