site_name: django-eventlog
docs_dir: docs/
site_dir: .docsbuild/
repo_url: https://github.com/bartTC/django-eventlog
edit_uri: edit/main/docs/
use_directory_urls: false

plugins:
  - include-markdown

extra:
  generator: true

theme:
  logo: https://github.com/bartTC/django-eventlog/raw/main/docs/_static/logo.webp
  palette:
    primary: indigo
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Installation & Usage: installation.md
  - Settings: settings.md
  - Testing: testing.md